anna-money/marshmallow-recipe

- .github/workflows/ci.yml
- marshmallow_recipe/__init__.py
- marshmallow_recipe/naming_strategy.py
- tests/test_naming_strategy.py
> Customize capital camel case and add camel case

- marshmallow_recipe/__init__.py
- marshmallow_recipe/bake.py
- marshmallow_recipe/fields.py
- tests/test_get_field_for.py
Unify behaviour of nested_field in line with string_field/bool_field
> Unify behaviour of nested_field in line with str_field/bool_field

- marshmallow_recipe/bake.py
- marshmallow_recipe/fields.py
- tests/test_get_field_for.py
> Support decimal field

- marshmallow_recipe/__init__.py
- marshmallow_recipe/bake.py
- marshmallow_recipe/fields.py
- marshmallow_recipe/metadata.py
- marshmallow_recipe/missing.py
- tests/test_get_field_for.py
- tests/test_serialization.py
> Support metadata

- marshmallow_recipe/bake.py
- marshmallow_recipe/fields.py
- tests/test_get_field_for.py
> Support int field

- marshmallow_recipe/bake.py
- marshmallow_recipe/fields.py
- tests/test_get_field_for.py
> Support float field

- marshmallow_recipe/bake.py
- marshmallow_recipe/fields.py
- tests/test_get_field_for.py
> Support uuid field

- marshmallow_recipe/bake.py
- marshmallow_recipe/fields.py
- tests/test_get_field_for.py
This PR adds support of list[T], List[T], dict[str, Any] and Dict[str, Any].
> Support list and dict

- marshmallow_recipe/bake.py
- marshmallow_recipe/fields.py
- tests/test_get_field_for.py
> Support datetime and date

- marshmallow_recipe/fields.py
- tests/test_get_field_for.py
> Fix deprecation warnings

- marshmallow_recipe/serialization.py
- tests/test_serialization.py
https://marshmallow.readthedocs.io/en/stable/upgrading.html#validation-does-not-occur-on-serialization
> Validate before dump for marshmallow3

- tests/test_serialization.py
> Add test details for dumping invalid value

- marshmallow_recipe/serialization.py
> Move many to schema

- marshmallow_recipe/naming_case.py
Default naming case should return the same name
> Fix default naming case

- marshmallow_recipe/__init__.py
- marshmallow_recipe/serialization.py
To grab all necessary schemas from one place
> Add EmptySchema

- marshmallow_recipe/bake.py
- marshmallow_recipe/fields.py
- tests/test_get_field_for.py
- tests/test_serialization.py
> Support enum

- marshmallow_recipe/fields.py
- marshmallow_recipe/metadata.py
- tests/test_validation.py
> Support validation

- marshmallow_recipe/fields.py
- tests/test_serialization.py
> Allow default value for required fields

- marshmallow_recipe/bake.py
- marshmallow_recipe/fields.py
- tests/test_get_field_for.py
- tests/test_serialization.py
> Support any 

- CHANGELOG.md
- marshmallow_recipe/__init__.py
- marshmallow_recipe/fields.py
- marshmallow_recipe/metadata.py
- tests/test_get_field_for.py
Need to specify a custom format for datetime fields
> Add datetime_metadata

- .github/workflows/ci.yml
> Add python 3.11 to CI

- .github/workflows/ci.yml
- tests/test_serialization.py
Just to be sure that this case works the same in all supported envs
> Add test for datetime in isodate without milliseconds

- marshmallow_recipe/__init__.py
- marshmallow_recipe/bake.py
- marshmallow_recipe/metadata.py
- tests/test_validation.py
> Allow to validate list item

- CHANGELOG.md
- marshmallow_recipe/__init__.py
- marshmallow_recipe/bake.py
- marshmallow_recipe/fields.py
- tests/test_get_field_for.py
- tests/test_serialization.py
To support dict[str, int] and so on.
> Support typed dict value

- CHANGELOG.md
- marshmallow_recipe/__init__.py
- marshmallow_recipe/bake.py
- marshmallow_recipe/fields.py
- tests/test_get_field_for.py
- tests/test_serialization.py
To support dict[int, Any] and so on.
> Support typed dict key

- CHANGELOG.md
- marshmallow_recipe/__init__.py
- marshmallow_recipe/serialization.py
- tests/test_serialization.py
- tests/test_validation.py
Before it might be possible to produce invalid data on dump.
> Validate dumped data against its schema for marshmallow2

- marshmallow_recipe/__init__.py
- marshmallow_recipe/bake.py
- marshmallow_recipe/naming_case.py
- marshmallow_recipe/options.py
- tests/test_get_field_for.py
- tests/test_naming_case.py
- tests/test_serialization.py
1. Calling bake_schema should reuse already generated schemas
2. NamingCase should not be propagated through object hierarchy
> Batch of fixes

- marshmallow_recipe/bake.py
- marshmallow_recipe/fields.py
- tests/test_get_field_for.py
- tests/test_serialization.py
typing.Set/typing.FrozenSet, set/frozenset are supported.
> Support set and frozenset

- marshmallow_recipe/bake.py
- marshmallow_recipe/fields.py
- marshmallow_recipe/hooks.py
- marshmallow_recipe/metadata.py
https://docs.python.org/3/library/typing.html#deprecated-aliases
> Stop using deprecated typing aliases

- README.md
- marshmallow_recipe/bake.py
- tests/test_get_field_for.py
Enables to specify these immutable abstractions.
> Support Sequence/Set/Mapping

- .github/workflows/ci.yml
- setup.py
https://discuss.python.org/t/python-3-12-0rc2-final-release-candidate-released
> Support python 3.12

- Makefile
- marshmallow_recipe/__init__.py
- marshmallow_recipe/bake.py
- marshmallow_recipe/fields.py
- marshmallow_recipe/hooks.py
- marshmallow_recipe/options.py
- marshmallow_recipe/serialization.py
- requirements-dev.txt
- tests/test_get_field_for.py
Also, removal of redundant casts and typings.
> Switch to pyright

- marshmallow_recipe/bake.py
- requirements-dev.txt
- setup.py
Functions get_origin and get_args from typing work fine.
> Stop using typing_inspect

- marshmallow_recipe/__init__.py
- marshmallow_recipe/bake.py
- marshmallow_recipe/metadata.py
- tests/test_get_field_for.py
> Rework metadata class and use it where possible

- marshmallow_recipe/__init__.py
- marshmallow_recipe/fields.py
- marshmallow_recipe/validator.py
1. Expose ValidationFunc to simplify metadata method signatures
2. Allow to specify array of ValidationFunc
3. Expose ValidationError to raise in validators
> Improve validation support

- marshmallow_recipe/__init__.py
- marshmallow_recipe/bake.py
- marshmallow_recipe/fields.py
- marshmallow_recipe/metadata.py
- tests/test_get_field_for.py
- tests/test_serialization.py
It should work on dump and on load
> Add strip_whitespace to str field

- marshmallow_recipe/fields.py
- marshmallow_recipe/metadata.py
- tests/test_serialization.py
To normalise data came from frontend
> Add post_load delegate to str field

- marshmallow_recipe/fields.py
- marshmallow_recipe/serialization.py
Related to this conversation https://github.com/anna-money/marshmallow-recipe/pull/163#discussion_r2030453213
> Make cls/data positional arguments only

- CHANGELOG.md
- marshmallow_recipe/fields.py
- marshmallow_recipe/metadata.py
We have 2 by default now, however something it might be needed to disable places completely.
> Allow to set no places for decimal

- README.md
- marshmallow_recipe/bake.py
- marshmallow_recipe/generics.py
- tests/test_get_field_for.py
- tests/test_serialization.py
Introduced `NewType` support
https://docs.python.org/3/library/typing.html#newtype
> Support typing.NewType

- marshmallow_recipe/__init__.py
- marshmallow_recipe/naming_case.py
- tests/test_naming_case.py
Not that frequent one, but unfortunately used
> Upper snake case
